repos:
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: poetry run pytest --cov=topics tests # poetry run pytest --cov=topics  --cov-report=xml tests
        language: system
        pass_filenames: false
        always_run: true