repos:
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: poetry run pytest --cov=topics tests
        language: system
        pass_filenames: false
        always_run: true